name: mockserver
description: A mock server for Dart to accelerate development when the server is not ready yet.
version: 1.4.0
homepage: https://github.com/mauriciotogneri/mockserver-dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.10.1
  test: ^1.15.3